apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lmol5vsjm-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lmol5vsjm-nodejs 
  name: lmol5vsjm-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: lmol5vsjm-nodejs 
